-module(timezone_list).
-export([timezones/0]).


timezones() -> [
	{"ACDT",  +10,30, <<"Australian Central Daylight Savings Time">>},
	{"ACST",  +09,30, <<"Australian Central Standard Time">>},
	{"ACT",   -05,00, <<"Acre Time">>},
	{"ACT",   +08,00, <<"ASEAN Common Time">>},
	{"ADT",   -03,00, <<"Atlantic Daylight Time">>},
	{"AEDT",  +11,00, <<"Australian Eastern Daylight Savings Time">>},
	{"AEST",  +10,00, <<"Australian Eastern Standard Time">>},
	{"AFT",   +04,30, <<"Afghanistan Time">>},
	{"AKDT",  -08,00, <<"Alaska Daylight Time">>},
	{"AKST",  -09,00, <<"Alaska Standard Time">>},
	{"AMST",  -03,00, <<"Amazon Summer Time">>},
	{"AMST",  +05,00, <<"Armenia Summer Time">>},
	{"AMT",   -04,00, <<"Amazon Time">>},
	{"AMT",   +04,00, <<"Armenia Time">>},
	{"ART",   -03,00, <<"Argentina Time">>},
	{"AST",   +03,00, <<"Arabia Standard Time">>},
	{"AST",   -04,00, <<"Atlantic Standard Time">>},
	{"AWDT",  +09,00, <<"Australian Western Daylight Time">>},
	{"AWST",  +08,00, <<"Australian Western Standard Time">>},
	{"AZOST", -01,00, <<"Azores Standard Time">>},
	{"AZT",   +04,00, <<"Azerbaijan Time">>},
	{"BDT",   +08,00, <<"Brunei Time">>},
	{"BDT",   +06,00, <<"Bangladesh Daylight Time">>},
	{"BIOT",  +06,00, <<"British Indian Ocean Time">>},
	{"BIT",   -12,00, <<"Baker Island Time">>},
	{"BOT",   -04,00, <<"Bolivia Time">>},
	{"BRST",  -02,00, <<"Brasilia Summer Time">>},
	{"BRT",   -03,00, <<"Brasilia Time">>},
	{"BST",   +01,00, <<"British Summer Time">>},
	{"BST",   +06,00, <<"Bangladesh Standard Time">>},
	{"BST",   +11,00, <<"Bougainville Standard Time">>},
	{"BTT",   +06,00, <<"Bhutan Time">>},
	{"CAT",   +02,00, <<"Central Africa Time">>},
	{"CCT",   +06,30, <<"Cocos Islands Time">>},
	{"CDT",   -05,00, <<"Central Daylight Time (North America)">>},
	{"CDT",   -04,00, <<"Cuba Daylight Time">>},
	{"CEDT",  +02,00, <<"Central European Daylight Time">>},
	{"CEST",  +02,00, <<"Central European Summer Time">>},
	{"CET",   +01,00, <<"Central European Time">>},
	{"CHADT", +13,45, <<"Chatham Daylight Time">>},
	{"CHAST", +12,45, <<"Chatham Standard Time">>},
	{"CHOT",  +08,00, <<"Choibalsan">>},
	{"ChST",  +10,00, <<"Chamorro Standard Time">>},
	{"CHUT",  +10,00, <<"Chuuk Time">>},
	{"CIST",  -08,00, <<"Clipperton Island Standard Time">>},
	{"CIT",   +08,00, <<"Central Indonesia Time">>},
	{"CKT",   -10,00, <<"Cook Island Time">>},
	{"CLST",  -03,00, <<"Chile Summer Time">>},
	{"CLT",   -04,00, <<"Chile Standard Time">>},
	{"COST",  -04,00, <<"Colombia Summer Time">>},
	{"COT",   -05,00, <<"Colombia Time">>},
	{"CST",   -06,00, <<"Central Standard Time (North America)">>},
	{"CST",   +08,00, <<"China Standard Time">>},
	{"CST",   +09,30, <<"Central Standard Time (Australia)">>},
	{"CST",   +10,30, <<"Central Summer Time (Australia)">>},
	{"CST",   -05,00, <<"Cuba Standard Time">>},
	{"CT",    +08,00, <<"China time">>},
	{"CVT",   -01,00, <<"Cape Verde Time">>},
	{"CWST",  +08,45, <<"Central Western Standard Time (Australia) (unofficial)">>},
	{"CXT",   +07,00, <<"Christmas Island Time">>},
	{"DAVT",  +07,00, <<"Davis Time">>},
	{"DDUT",  +10,00, <<"Dumont d'Urville Time">>},
	{"DFT",   +01,00, <<"AIX specific equivalent of Central European Time">>},
	{"EASST", -05,00, <<"Easter Island Standard Summer Time">>},
	{"EAST",  -06,00, <<"Easter Island Standard Time">>},
	{"EAT",   +03,00, <<"East Africa Time">>},
	{"ECT",   -04,00, <<"Eastern Caribbean Time">>},
	{"ECT",   -05,00, <<"Ecuador Time">>},
	{"EDT",   -04,00, <<"Eastern Daylight Time (North America)">>},
	{"EEDT",  +03,00, <<"Eastern European Daylight Time">>},
	{"EEST",  +03,00, <<"Eastern European Summer Time">>},
	{"EET",   +02,00, <<"Eastern European Time">>},
	{"EGST",  +00,00, <<"Eastern Greenland Summer Time">>},
	{"EGT",   -01,00, <<"Eastern Greenland Time">>},
	{"EIT",   +09,00, <<"Eastern Indonesian Time">>},
	{"EST",   -05,00, <<"Eastern Standard Time (North America)">>},
	{"EST",   +10,00, <<"Eastern Standard Time (Australia)">>},
	{"FET",   +03,00, <<"Further-eastern European Time">>},
	{"FJT",   +12,00, <<"Fiji Time">>},
	{"FKST",  -03,00, <<"Falkland Islands Standard Time">>},
	{"FKST",  -03,00, <<"Falkland Islands Summer Time">>},
	{"FKT",   -04,00, <<"Falkland Islands Time">>},
	{"FNT",   -02,00, <<"Fernando de Noronha Time">>},
	{"GALT",  -06,00, <<"Galapagos Time">>},
	{"GAMT",  -09,00, <<"Gambier Islands">>},
	{"GET",   +04,00, <<"Georgia Standard Time">>},
	{"GFT",   -03,00, <<"French Guiana Time">>},
	{"GILT",  +12,00, <<"Gilbert Island Time">>},
	{"GIT",   -09,00, <<"Gambier Island Time">>},
	{"GMT",   +00,00, <<"Greenwich Mean Time">>},
	{"GST",   -02,00, <<"South Georgia and the South Sandwich Islands">>},
	{"GST",   +04,00, <<"Gulf Standard Time">>},
	{"GYT",   -04,00, <<"Guyana Time">>},
	{"HADT",  -09,00, <<"Hawaii-Aleutian Daylight Time">>},
	{"HAEC",  +02,00, <<"Heure Avancée d'Europe Centrale (CEST)">>},
	{"HAST",  -10,00, <<"Hawaii-Aleutian Standard Time">>},
	{"HKT",   +08,00, <<"Hong Kong Time">>},
	{"HMT",   +05,00, <<"Heard and McDonald Islands Time">>},
	{"HOVT",  +07,00, <<"Khovd Time">>},
	{"HST",   -10,00, <<"Hawaii Standard Time">>},
	{"ICT",   +07,00, <<"Indochina Time">>},
	{"IDT",   +03,00, <<"Israel Daylight Time">>},
	{"IOT",   +03,00, <<"Indian Ocean Time">>},
	{"IRDT",  +04,30, <<"Iran Daylight Time">>},
	{"IRKT",  +08,00, <<"Irkutsk Time">>},
	{"IRST",  +03,30, <<"Iran Standard Time">>},
	{"IST",   +01,00, <<"Irish Standard Time">>},
	{"IST2",  +05,30, <<"Indian Standard Time">>},
	{"IST3",  +02,00, <<"Israel Standard Time">>},
	{"JST",   +09,00, <<"Japan Standard Time">>},
	{"KGT",   +06,00, <<"Kyrgyzstan time">>},
	{"KOST",  +11,00, <<"Kosrae Time">>},
	{"KRAT",  +07,00, <<"Krasnoyarsk Time">>},
	{"KST",   +09,00, <<"Korea Standard Time">>},
	{"LHST",  +10,30, <<"Lord Howe Standard Time">>},
	{"LHST",  +11,00, <<"Lord Howe Summer Time">>},
	{"LINT",  +14,00, <<"Line Islands Time">>},
	{"MAGT",  +12,00, <<"Magadan Time">>},
	{"MART",  -09,30, <<"Marquesas Islands Time">>},
	{"MAWT",  +05,00, <<"Mawson Station Time">>},
	{"MDT",   -06,00, <<"Mountain Daylight Time (North America)">>},
	{"MET",   +01,00, <<"Middle European Time">>},
	{"MEST",  +02,00, <<"Middle European Saving Time">>},
	{"MHT",   +12,00, <<"Marshall Islands">>},
	{"MIST",  +11,00, <<"Macquarie Island Station Time">>},
	{"MIT",   -09,30, <<"Marquesas Islands Time">>},
	{"MMT",   +06,30, <<"Myanmar Time">>},
	{"MSK",   +03,00, <<"Moscow Time">>},
	{"MST",   +08,00, <<"Malaysia Standard Time">>},
	{"MST",   -07,00, <<"Mountain Standard Time (North America)">>},
	{"MST",   +06,30, <<"Myanmar Standard Time">>},
	{"MUT",   +04,00, <<"Mauritius Time">>},
	{"MVT",   +05,00, <<"Maldives Time">>},
	{"MYT",   +08,00, <<"Malaysia Time">>},
	{"NCT",   +11,00, <<"New Caledonia Time">>},
	{"NDT",   -02,30, <<"Newfoundland Daylight Time">>},
	{"NFT",   +11,30, <<"Norfolk Time">>},
	{"NPT",   +05,45, <<"Nepal Time">>},
	{"NST",   -03,30, <<"Newfoundland Standard Time">>},
	{"NT",    -03,30, <<"Newfoundland Time">>},
	{"NUT",   -11,00, <<"Niue Time">>},
	{"NZDT",  +13,00, <<"New Zealand Daylight Time">>},
	{"NZST",  +12,00, <<"New Zealand Standard Time">>},
	{"OMST",  +06,00, <<"Omsk Time">>},
	{"ORAT",  +05,00, <<"Oral Time">>},
	{"PDT",   -07,00, <<"Pacific Daylight Time (North America)">>},
	{"PET",   -05,00, <<"Peru Time">>},
	{"PETT",  +12,00, <<"Kamchatka Time">>},
	{"PGT",   +10,00, <<"Papua New Guinea Time">>},
	{"PHOT",  +13,00, <<"Phoenix Island Time">>},
	{"PKT",   +05,00, <<"Pakistan Standard Time">>},
	{"PMDT",  -02,00, <<"Saint Pierre and Miquelon Daylight time">>},
	{"PMST",  -03,00, <<"Saint Pierre and Miquelon Standard Time">>},
	{"PONT",  +11,00, <<"Pohnpei Standard Time">>},
	{"PST",   -08,00, <<"Pacific Standard Time (North America)">>},
	{"PST",   +08,00, <<"Philippine Standard Time">>},
	{"PYST",  -03,00, <<"Paraguay Summer Time (South America)">>},
	{"PYT",   -04,00, <<"Paraguay Time (South America)">>},
	{"RET",   +04,00, <<"Réunion Time">>},
	{"ROTT",  -03,00, <<"Rothera Research Station Time">>},
	{"SAKT",  +11,00, <<"Sakhalin Island time">>},
	{"SAMT",  +04,00, <<"Samara Time">>},
	{"SAST",  +02,00, <<"South African Standard Time">>},
	{"SBT",   +11,00, <<"Solomon Islands Time">>},
	{"SCT",   +04,00, <<"Seychelles Time">>},
	{"SGT",   +08,00, <<"Singapore Time">>},
	{"SLST",  +05,30, <<"Sri Lanka Standard Time">>},
	{"SRET",  +11,00, <<"Srednekolymsk Time">>},
	{"SRT",   -03,00, <<"Suriname Time">>},
	{"SST",   -11,00, <<"Samoa Standard Time">>},
	{"SST",   +08,00, <<"Singapore Standard Time">>},
	{"SYOT",  +03,00, <<"Showa Station Time">>},
	{"TAHT",  -10,00, <<"Tahiti Time">>},
	{"THA",   +07,00, <<"Thailand Standard Time">>},
	{"TFT",   +05,00, <<"Indian/Kerguelen">>},
	{"TJT",   +05,00, <<"Tajikistan Time">>},
	{"TKT",   +13,00, <<"Tokelau Time">>},
	{"TLT",   +09,00, <<"Timor Leste Time">>},
	{"TMT",   +05,00, <<"Turkmenistan Time">>},
	{"TOT",   +13,00, <<"Tonga Time">>},
	{"TVT",   +12,00, <<"Tuvalu Time">>},
	{"UCT",   +00,00, <<"Coordinated Universal Time">>},
	{"ULAT",  +08,00, <<"Ulaanbaatar Time">>},
	{"USZ1",  +02,00, <<"Kaliningrad Time">>},
	{"UTC",   +00,00, <<"Coordinated Universal Time">>},
	{"UYST",  -02,00, <<"Uruguay Summer Time">>},
	{"UYT",   -03,00, <<"Uruguay Standard Time">>},
	{"UZT",   +05,00, <<"Uzbekistan Time">>},
	{"VET",   -04,30, <<"Venezuelan Standard Time">>},
	{"VLAT",  +10,00, <<"Vladivostok Time">>},
	{"VOLT",  +04,00, <<"Volgograd Time">>},
	{"VOST",  +06,00, <<"Vostok Station Time">>},
	{"VUT",   +11,00, <<"Vanuatu Time">>},
	{"WAKT",  +12,00, <<"Wake Island Time">>},
	{"WAST",  +02,00, <<"West Africa Summer Time">>},
	{"WAT",   +01,00, <<"West Africa Time">>},
	{"WEDT",  +01,00, <<"Western European Daylight Time">>},
	{"WEST",  +01,00, <<"Western European Summer Time">>},
	{"WET",   +00,00, <<"Western European Time">>},
	{"WIT",   +07,00, <<"Western Indonesian Time">>},
	{"WST",   +08,00, <<"Western Standard Time">>},
	{"YAKT",  +09,00, <<"Yakutsk Time">>},
	{"YEKT",  +05,00, <<"Yekaterinburg Time">>},
	{"Z",     +00,00, <<"Zulu Time (UTC)">>}
].
